[package]
name = "swc_plugin_mark_expressions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swc_core = { version = "0.81.*", features = ["ecma_plugin_transform", "ecma_ast", "ecma_parser", "ecma_utils", "common"] }

[dev-dependencies]
testing = "0.35.19"